from scipy.stats import wasserstein_distance
import numpy as np


# This code was generated by Microsoft Copilot
def wasserstein_distance(u_values, v_values, u_weights, v_weights):
    distance = wasserstein_distance(u_values, v_values, u_weights, v_weights)
    return distance
