# This code was generated by OpenAI ChatGPT 3.5

import numpy as np
from scipy.stats import norm

lower_bound = -1
upper_bound = 1
probability = norm.cdf(upper_bound) - norm.cdf(lower_bound)
print("Probability of observing values within the interval [-1, 1]:", probability)

